version: "3.9"

services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - "DJANGO_SETTINGS_MODULE=chat_bot.settings"
      - "wzttne=${wzttne}"
      - "j_j=${j_j}"
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - action-server

  action-server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - .:/app
